# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://sensorsunleashed.com
title: Sensors Unleashed
email: ole@mnissen.dk
author: Ole Nissen
description: > # "Write an awesome description for your new site here.
  The goal of Sensors Unleashed is to create a community driven development
  of a simple, yet powerfull interconnection between wireless devices. The project
  will be completely open source and follow open standards. Open Hardware,
  Open Source Software, CoAP, Contiki....
copyright: 'Copyright &copy; 2016 Ole Nissen. All Rights Reserved.'
credits: 'Credits: Sensors Unleashed is a free to use, open source wireless sensor network started by Ole Nissen'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/SensorsUnleashed
  - title: linkedin
    url: https://www.linkedin.com/in/ole-nissen-36b38110?trk=hp-identity-name
